# Generated by Django 4.1.7 on 2023-05-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_tags_alter_blog_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
