# Generated by Django 4.1.7 on 2023-05-16 18:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EducationPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("image", models.ImageField(upload_to="")),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="content"
                    ),
                ),
                ("date_upload", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Education Post",
                "verbose_name_plural": "Education Posts",
                "ordering": ("id", "title"),
            },
        ),
        migrations.CreateModel(
            name="Vocabulary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                (
                    "definition",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="definition"
                    ),
                ),
                ("date_upload", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vocabulary",
                "verbose_name_plural": "Vocabulary",
                "ordering": ("id", "title"),
            },
        ),
    ]
