# Generated by Django 4.1.7 on 2023-04-11 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=20, verbose_name="period")),
            ],
        ),
        migrations.AlterField(
            model_name="company",
            name="cik",
            field=models.CharField(max_length=20, null=True, verbose_name="cik"),
        ),
        migrations.AlterField(
            model_name="company",
            name="easy_to_borrow",
            field=models.BooleanField(null=True, verbose_name="easy_to_borrow"),
        ),
        migrations.AlterField(
            model_name="company",
            name="exchange",
            field=models.CharField(max_length=10, null=True, verbose_name="exchange"),
        ),
        migrations.AlterField(
            model_name="company",
            name="fractionable",
            field=models.BooleanField(null=True, verbose_name="fractionable"),
        ),
        migrations.AlterField(
            model_name="company",
            name="industry",
            field=models.CharField(max_length=100, null=True, verbose_name="industry"),
        ),
        migrations.AlterField(
            model_name="company",
            name="marginable",
            field=models.BooleanField(null=True, verbose_name="marginable"),
        ),
        migrations.AlterField(
            model_name="company",
            name="min_size_order",
            field=models.FloatField(null=True, verbose_name="min_size_order"),
        ),
        migrations.AlterField(
            model_name="company",
            name="min_trade_increment",
            field=models.FloatField(null=True, verbose_name="min_trade_increment"),
        ),
        migrations.AlterField(
            model_name="company",
            name="price_increment",
            field=models.FloatField(null=True, verbose_name="price_increment"),
        ),
        migrations.AlterField(
            model_name="company",
            name="sector",
            field=models.CharField(max_length=100, null=True, verbose_name="sector"),
        ),
        migrations.AlterField(
            model_name="company",
            name="shortable",
            field=models.BooleanField(null=True, verbose_name="shortable"),
        ),
        migrations.AlterField(
            model_name="company",
            name="tradable",
            field=models.BooleanField(null=True, verbose_name="tradable"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="accumulated_deprec_amort",
            field=models.BigIntegerField(
                null=True, verbose_name="accumulated_deprec_amort"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="capital_lease_obligations",
            field=models.BigIntegerField(
                null=True, verbose_name="capital_lease_obligations"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="cash_and_equiv",
            field=models.BigIntegerField(null=True, verbose_name="cash_and_equiv"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="cash_and_shortinvestment",
            field=models.BigIntegerField(
                null=True, verbose_name="cash_and_shortinvestment"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="common_stock",
            field=models.BigIntegerField(null=True, verbose_name="common_stock"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="common_stock_shares_outstand",
            field=models.BigIntegerField(
                null=True, verbose_name="common_stock_shares_outstan"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="current_accounts_payable",
            field=models.BigIntegerField(
                null=True, verbose_name="current_accounts_payable"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="current_debt",
            field=models.BigIntegerField(null=True, verbose_name="current_debt"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="current_long_term_debt",
            field=models.BigIntegerField(
                null=True, verbose_name="current_long_term_debt"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="current_net_recievables",
            field=models.BigIntegerField(
                null=True, verbose_name="current_net_recievables"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="deferred_revenue",
            field=models.BigIntegerField(null=True, verbose_name="deferred_revenue"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="goodwill",
            field=models.BigIntegerField(null=True, verbose_name="goodwill"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="intagible_assets",
            field=models.BigIntegerField(null=True, verbose_name="intangible_assets"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="intagible_assets_exc_goodwill",
            field=models.BigIntegerField(
                null=True, verbose_name="intangible_assets_exc_goodwill"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="inventory",
            field=models.BigIntegerField(null=True, verbose_name="inventory"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="investments",
            field=models.BigIntegerField(null=True, verbose_name="investments"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="long_term_debt",
            field=models.BigIntegerField(null=True, verbose_name="long_term_debt"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="long_term_investment",
            field=models.BigIntegerField(
                null=True, verbose_name="long_term_investment"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="long_term_noncurrent",
            field=models.BigIntegerField(
                null=True, verbose_name="long_term_noncurrent"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="other_current_assets",
            field=models.BigIntegerField(
                null=True, verbose_name="other_current_assets"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="other_current_liab",
            field=models.BigIntegerField(null=True, verbose_name="other_current_liab"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="other_noncurrent_assets",
            field=models.BigIntegerField(
                null=True, verbose_name="other_noncurrent_assets"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="other_noncurrent_liab",
            field=models.BigIntegerField(
                null=True, verbose_name="other_noncurrent_liab"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="proprety_plan_equipment",
            field=models.BigIntegerField(
                null=True, verbose_name="property_plan_equipment"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="retained_earnings",
            field=models.BigIntegerField(null=True, verbose_name="retained_earnings"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="short_long_term_debt_total",
            field=models.BigIntegerField(
                null=True, verbose_name="short_long_term_debt_total"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="short_term_debt",
            field=models.BigIntegerField(null=True, verbose_name="short_term_debt"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="short_term_investment",
            field=models.BigIntegerField(
                null=True, verbose_name="short_term_investment"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="total_assets",
            field=models.BigIntegerField(null=True, verbose_name="total_assets"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="total_current_assets",
            field=models.BigIntegerField(
                null=True, verbose_name="total_current_assets"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="total_current_liabilities",
            field=models.BigIntegerField(
                null=True, verbose_name="total_current_liabilities"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="total_liabilities",
            field=models.BigIntegerField(null=True, verbose_name="total_liabilities"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="total_non_current_assets",
            field=models.BigIntegerField(
                null=True, verbose_name="total_noncurrent_assets"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="total_noncurrent_liab",
            field=models.BigIntegerField(
                null=True, verbose_name="total_noncurrent_liab"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="total_shareholder_equity",
            field=models.BigIntegerField(
                null=True, verbose_name="totak_shareholder_equity"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="treasury_stock",
            field=models.BigIntegerField(null=True, verbose_name="treasury_stock"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="capital_expenditures",
            field=models.BigIntegerField(
                null=True, verbose_name="capital_expenditures"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="cashflow_from_financing",
            field=models.BigIntegerField(
                null=True, verbose_name="cashflow_from_financing"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="cashflow_from_investment",
            field=models.BigIntegerField(
                null=True, verbose_name="cashflow_from_investment"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="change_in_cash_and_equiv",
            field=models.BigIntegerField(
                null=True, verbose_name="change_in_cash_and_equiv"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="change_in_exchange_rate",
            field=models.BigIntegerField(
                null=True, verbose_name="change_in_exchange_rate"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="change_in_inventory",
            field=models.BigIntegerField(null=True, verbose_name="change_in_inventory"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="change_in_oper_assets",
            field=models.BigIntegerField(
                null=True, verbose_name="change_in_oper_assets"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="change_in_oper_liab",
            field=models.BigIntegerField(null=True, verbose_name="change_in_oper_liab"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="change_in_recievables",
            field=models.BigIntegerField(
                null=True, verbose_name="change_in_recievables"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="deprec_depletion_amort",
            field=models.BigIntegerField(null=True, verbose_name="deprec_deplet_amort"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="dividend_payout",
            field=models.BigIntegerField(null=True, verbose_name="dividend_payout"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="dividend_payout_common_stock",
            field=models.BigIntegerField(
                null=True, verbose_name="dividend_payout_common_stock"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="dividend_payout_preferred_stock",
            field=models.BigIntegerField(
                null=True, verbose_name="dividend_payout_preferred_stock"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="net_income",
            field=models.BigIntegerField(null=True, verbose_name="net_income"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="operating_cashflow",
            field=models.BigIntegerField(null=True, verbose_name="operating_cashflow"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="payment_for_repurchase_of_equity",
            field=models.BigIntegerField(
                null=True, verbose_name="payment_for_repurchase_equity"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="payment_for_repurchase_of_preferred_stock",
            field=models.BigIntegerField(
                null=True, verbose_name="payment_for_repurchase_of_preferred_stock"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="payment_from_oper_activities",
            field=models.BigIntegerField(
                null=True, verbose_name="payment_from_oper_activities"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="payments_for_repurchase_of_common_stocks",
            field=models.BigIntegerField(
                null=True,
                verbose_name="paymenys_for_repayment_of_repurchase_common_stocks",
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="proceeds_from_issuance_of_common_stocks",
            field=models.BigIntegerField(
                null=True, verbose_name="proceeds_from_issuance_of_common_stocks"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="proceeds_from_issuance_of_long_term_debt",
            field=models.BigIntegerField(
                null=True, verbose_name="proceeds_from_issuance_of_long_term_debt"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="proceeds_from_issuance_of_preferres_stocks",
            field=models.BigIntegerField(
                null=True, verbose_name="proceeds_from_issuance_of_preferred_stocks"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="proceeds_from_oper_activities",
            field=models.BigIntegerField(
                null=True, verbose_name="proceeds_from_oper_activities"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="proceeds_from_repayment_of_short_term_debt",
            field=models.BigIntegerField(
                null=True, verbose_name="proceeds_from_repayment_of_short_term_debt"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="proceeds_from_repurchase_of_equity",
            field=models.BigIntegerField(
                null=True, verbose_name="proceeds_of_repurchase_equity"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="proceeds_from_sale_of_treasury_stock",
            field=models.BigIntegerField(
                null=True, verbose_name="proceeds_from_sale_of_treasury_stock"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="profit_loss",
            field=models.BigIntegerField(null=True, verbose_name="profit_loss"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="beta",
            field=models.FloatField(null=True, verbose_name="beta"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="book_value",
            field=models.FloatField(null=True, verbose_name="book_value"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="diluted_eps_ttm",
            field=models.FloatField(null=True, verbose_name="diluted_eps_ttm"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="dividend_per_share",
            field=models.FloatField(null=True, verbose_name="dividend_per_share"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="dividend_yield",
            field=models.FloatField(null=True, verbose_name="dividend_yield"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="ebitda",
            field=models.BigIntegerField(null=True, verbose_name="ebitda"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="eps",
            field=models.FloatField(null=True, verbose_name="eps"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="ev2ebitda",
            field=models.FloatField(null=True, verbose_name="ev2ebitda"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="ev2revenue",
            field=models.FloatField(null=True, verbose_name="ev2revenue"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="forward_pe",
            field=models.FloatField(null=True, verbose_name="forward_pe"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="gross_profit_ttm",
            field=models.BigIntegerField(null=True, verbose_name="gross_profit_ttm"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="market_cap",
            field=models.BigIntegerField(null=True, verbose_name="market_cap"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="operating_margin_ttm",
            field=models.FloatField(null=True, verbose_name="operating_margin_ttm"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="pe_ratio",
            field=models.FloatField(null=True, verbose_name="pe_ratio"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="peg_ratio",
            field=models.FloatField(null=True, verbose_name="peg_ratio"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="price2book_ratio",
            field=models.FloatField(null=True, verbose_name="price2book_ratio"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="price2sales_ratio",
            field=models.FloatField(null=True, verbose_name="price2sales_ratio"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="profit_margin_ttm",
            field=models.FloatField(null=True, verbose_name="profit_margin_ttm"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="revenue_per_share",
            field=models.FloatField(null=True, verbose_name="revenue_per_share"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="revenue_ttm",
            field=models.BigIntegerField(null=True, verbose_name="revenue_ttm"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="roa_ttm",
            field=models.FloatField(null=True, verbose_name="roa_ttm"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="roe_ttm",
            field=models.FloatField(null=True, verbose_name="roe_ttm"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="shares_outstanding",
            field=models.BigIntegerField(null=True, verbose_name="shares_outstanding"),
        ),
        migrations.AlterField(
            model_name="companyfinratios",
            name="trailing_pe",
            field=models.FloatField(null=True, verbose_name="trailing_pe"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="comprehensive_income_net_of_tax",
            field=models.BigIntegerField(
                null=True, verbose_name="comprehensive_income_net_of_tax"
            ),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="cost_of_goos_sold",
            field=models.BigIntegerField(null=True, verbose_name="cost_of_goods_sold"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="cost_of_revenue",
            field=models.BigIntegerField(null=True, verbose_name="cost_of_revenue"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="depreciation",
            field=models.BigIntegerField(null=True, verbose_name="depreciation"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="depreciation_and_amortization",
            field=models.BigIntegerField(
                null=True, verbose_name="depreciation_and_amortization"
            ),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="ebit",
            field=models.BigIntegerField(null=True, verbose_name="ebit"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="ebitda",
            field=models.BigIntegerField(null=True, verbose_name="ebitda"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="gross_profit",
            field=models.BigIntegerField(null=True, verbose_name="gross_profit"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="income_before_tax",
            field=models.BigIntegerField(null=True, verbose_name="income_before_tax"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="income_tax_expense",
            field=models.BigIntegerField(null=True, verbose_name="income_tax_expense"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="interest_debt_expense",
            field=models.BigIntegerField(
                null=True, verbose_name="interest_debt_expense"
            ),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="interest_expense",
            field=models.BigIntegerField(null=True, verbose_name="interest_expense"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="interest_income",
            field=models.BigIntegerField(null=True, verbose_name="interest_income"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="investment_income_net",
            field=models.BigIntegerField(
                null=True, verbose_name="investment_income_net"
            ),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="net_income",
            field=models.BigIntegerField(null=True, verbose_name="net_income"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="net_income_from_contin_operations",
            field=models.BigIntegerField(
                null=True, verbose_name="net_income_from_contin_operations"
            ),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="net_interest_income",
            field=models.BigIntegerField(null=True, verbose_name="net interest income"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="non_interest_income",
            field=models.BigIntegerField(null=True, verbose_name="non_interest_income"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="operating_expenses",
            field=models.BigIntegerField(null=True, verbose_name="operating_expenses"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="operating_income",
            field=models.BigIntegerField(null=True, verbose_name="operating_income"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="other_nonoper_income",
            field=models.BigIntegerField(
                null=True, verbose_name="other_nonoper_income"
            ),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="rnd",
            field=models.BigIntegerField(null=True, verbose_name="rnd"),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="selling_general_and_admin",
            field=models.BigIntegerField(
                null=True, verbose_name="selling_general_and_admin"
            ),
        ),
        migrations.AlterField(
            model_name="companyincomestatement",
            name="total_revenue",
            field=models.BigIntegerField(null=True, verbose_name="total_revenue"),
        ),
        migrations.AlterField(
            model_name="stockprices",
            name="trade_count",
            field=models.BigIntegerField(null=True, verbose_name="trade_count"),
        ),
        migrations.AlterField(
            model_name="stockprices",
            name="volume",
            field=models.BigIntegerField(null=True, verbose_name="volume"),
        ),
        migrations.AlterField(
            model_name="stockprices",
            name="vwap",
            field=models.FloatField(null=True, verbose_name="vwap"),
        ),
        migrations.AddField(
            model_name="companycommon",
            name="period",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="investment.reportperiod",
            ),
        ),
    ]
