# Generated by Django 4.1.7 on 2023-04-17 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0004_alter_company_industry_alter_company_sector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange_name",
                    models.CharField(max_length=20, verbose_name="exchange_name"),
                ),
            ],
            options={
                "verbose_name": "Exchange name",
                "verbose_name_plural": "Exchange names",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SecurityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "security_type",
                    models.CharField(max_length=20, verbose_name="security_type"),
                ),
            ],
            options={
                "verbose_name": "Security type",
                "verbose_name_plural": "Security types",
                "ordering": ["id"],
            },
        ),
        migrations.AlterModelOptions(
            name="commodity",
            options={
                "ordering": ("id",),
                "verbose_name": "Commodity",
                "verbose_name_plural": "Commodities",
            },
        ),
        migrations.AlterModelOptions(
            name="digitalcurrency",
            options={
                "ordering": ("id",),
                "verbose_name": "Digital Currency",
                "verbose_name_plural": "Digital Currencies",
            },
        ),
        migrations.AlterModelOptions(
            name="indicator",
            options={
                "ordering": ("id",),
                "verbose_name": "Indicator",
                "verbose_name_plural": "Indicators",
            },
        ),
        migrations.AlterModelOptions(
            name="industry",
            options={
                "ordering": ("id",),
                "verbose_name": "Industry",
                "verbose_name_plural": "Industries",
            },
        ),
        migrations.AlterModelOptions(
            name="maturity",
            options={
                "ordering": ["id"],
                "verbose_name": "Maturity",
                "verbose_name_plural": "Maturities",
            },
        ),
        migrations.AlterModelOptions(
            name="newscategory",
            options={
                "ordering": ("id",),
                "verbose_name": "News Category",
                "verbose_name_plural": "News Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="newssentiment",
            options={
                "ordering": ["id"],
                "verbose_name": "News Sentiment",
                "verbose_name_plural": "News Sentiments",
            },
        ),
        migrations.AlterModelOptions(
            name="newstopics",
            options={
                "ordering": ("id",),
                "verbose_name": "News Topic",
                "verbose_name_plural": "News Topics",
            },
        ),
        migrations.AlterModelOptions(
            name="physicalcurrency",
            options={
                "ordering": ("id",),
                "verbose_name": "Physical Currency",
                "verbose_name_plural": "Physical Currencies",
            },
        ),
        migrations.AlterModelOptions(
            name="priceperiod",
            options={
                "ordering": ("id",),
                "verbose_name": "Price Period",
                "verbose_name_plural": "Price Periods",
            },
        ),
        migrations.AlterModelOptions(
            name="reportperiod",
            options={
                "ordering": ("id",),
                "verbose_name": "Report Period",
                "verbose_name_plural": "Report periods",
            },
        ),
        migrations.AlterModelOptions(
            name="sector",
            options={
                "ordering": ("id",),
                "verbose_name": "Sector",
                "verbose_name_plural": "Sectors",
            },
        ),
        migrations.AlterModelOptions(
            name="sourcedomain",
            options={
                "ordering": ("id",),
                "verbose_name": "Source Domain",
                "verbose_name_plural": "Source Domains",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="ipo_date",
            field=models.DateField(null=True, verbose_name="IPO_date"),
        ),
        migrations.AlterField(
            model_name="company",
            name="industry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="investment.industry"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="investment.sector"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="exchange",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="investment.exchange",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="security_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="investment.securitytype",
            ),
        ),
    ]
