# Generated by Django 4.1.7 on 2023-04-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0007_alter_industry_industry_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportperiod",
            options={
                "ordering": ("id",),
                "verbose_name": "Report Period",
                "verbose_name_plural": "Report Periods",
            },
        ),
        migrations.AlterField(
            model_name="sector",
            name="sector_name",
            field=models.CharField(max_length=50, verbose_name="sector_name"),
        ),
    ]
