# Generated by Django 4.1.7 on 2023-04-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "investment",
            "0010_alter_companyincomestatement_comprehensive_income_net_of_tax_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="companybalancesheet",
            name="accumulated_deprec_amort",
            field=models.FloatField(null=True, verbose_name="accumulated_deprec_amort"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="capital_lease_obligations",
            field=models.FloatField(
                null=True, verbose_name="capital_lease_obligations"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="cash_and_equiv",
            field=models.FloatField(null=True, verbose_name="cash_and_equiv"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="cash_and_shortinvestment",
            field=models.FloatField(null=True, verbose_name="cash_and_shortinvestment"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="common_stock",
            field=models.FloatField(null=True, verbose_name="common_stock"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="common_stock_shares_outstand",
            field=models.FloatField(
                null=True, verbose_name="common_stock_shares_outstan"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="current_accounts_payable",
            field=models.FloatField(null=True, verbose_name="current_accounts_payable"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="current_debt",
            field=models.FloatField(null=True, verbose_name="current_debt"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="current_long_term_debt",
            field=models.FloatField(null=True, verbose_name="current_long_term_debt"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="current_net_recievables",
            field=models.FloatField(null=True, verbose_name="current_net_recievables"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="deferred_revenue",
            field=models.FloatField(null=True, verbose_name="deferred_revenue"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="goodwill",
            field=models.FloatField(null=True, verbose_name="goodwill"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="intagible_assets",
            field=models.FloatField(null=True, verbose_name="intangible_assets"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="intagible_assets_exc_goodwill",
            field=models.FloatField(
                null=True, verbose_name="intangible_assets_exc_goodwill"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="inventory",
            field=models.FloatField(null=True, verbose_name="inventory"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="investments",
            field=models.FloatField(null=True, verbose_name="investments"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="long_term_debt",
            field=models.FloatField(null=True, verbose_name="long_term_debt"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="long_term_investment",
            field=models.FloatField(null=True, verbose_name="long_term_investment"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="long_term_noncurrent",
            field=models.FloatField(null=True, verbose_name="long_term_noncurrent"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="other_current_assets",
            field=models.FloatField(null=True, verbose_name="other_current_assets"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="other_current_liab",
            field=models.FloatField(null=True, verbose_name="other_current_liab"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="other_noncurrent_assets",
            field=models.FloatField(null=True, verbose_name="other_noncurrent_assets"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="other_noncurrent_liab",
            field=models.FloatField(null=True, verbose_name="other_noncurrent_liab"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="proprety_plan_equipment",
            field=models.FloatField(null=True, verbose_name="property_plan_equipment"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="retained_earnings",
            field=models.FloatField(null=True, verbose_name="retained_earnings"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="short_long_term_debt_total",
            field=models.FloatField(
                null=True, verbose_name="short_long_term_debt_total"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="short_term_debt",
            field=models.FloatField(null=True, verbose_name="short_term_debt"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="short_term_investment",
            field=models.FloatField(null=True, verbose_name="short_term_investment"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="total_assets",
            field=models.FloatField(null=True, verbose_name="total_assets"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="total_current_assets",
            field=models.FloatField(null=True, verbose_name="total_current_assets"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="total_current_liabilities",
            field=models.FloatField(
                null=True, verbose_name="total_current_liabilities"
            ),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="total_liabilities",
            field=models.FloatField(null=True, verbose_name="total_liabilities"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="total_non_current_assets",
            field=models.FloatField(null=True, verbose_name="total_noncurrent_assets"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="total_noncurrent_liab",
            field=models.FloatField(null=True, verbose_name="total_noncurrent_liab"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="total_shareholder_equity",
            field=models.FloatField(null=True, verbose_name="totak_shareholder_equity"),
        ),
        migrations.AlterField(
            model_name="companybalancesheet",
            name="treasury_stock",
            field=models.FloatField(null=True, verbose_name="treasury_stock"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="capital_expenditures",
            field=models.FloatField(null=True, verbose_name="capital_expenditures"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="cashflow_from_financing",
            field=models.FloatField(null=True, verbose_name="cashflow_from_financing"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="cashflow_from_investment",
            field=models.FloatField(null=True, verbose_name="cashflow_from_investment"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="change_in_cash_and_equiv",
            field=models.FloatField(null=True, verbose_name="change_in_cash_and_equiv"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="change_in_exchange_rate",
            field=models.FloatField(null=True, verbose_name="change_in_exchange_rate"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="change_in_inventory",
            field=models.FloatField(null=True, verbose_name="change_in_inventory"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="change_in_oper_assets",
            field=models.FloatField(null=True, verbose_name="change_in_oper_assets"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="change_in_oper_liab",
            field=models.FloatField(null=True, verbose_name="change_in_oper_liab"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="change_in_recievables",
            field=models.FloatField(null=True, verbose_name="change_in_recievables"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="deprec_depletion_amort",
            field=models.FloatField(null=True, verbose_name="deprec_deplet_amort"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="dividend_payout",
            field=models.FloatField(null=True, verbose_name="dividend_payout"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="dividend_payout_common_stock",
            field=models.FloatField(
                null=True, verbose_name="dividend_payout_common_stock"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="dividend_payout_preferred_stock",
            field=models.FloatField(
                null=True, verbose_name="dividend_payout_preferred_stock"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="net_income",
            field=models.FloatField(null=True, verbose_name="net_income"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="operating_cashflow",
            field=models.FloatField(null=True, verbose_name="operating_cashflow"),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="payment_for_repurchase_of_equity",
            field=models.FloatField(
                null=True, verbose_name="payment_for_repurchase_equity"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="payment_for_repurchase_of_preferred_stock",
            field=models.FloatField(
                null=True, verbose_name="payment_for_repurchase_of_preferred_stock"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="payment_from_oper_activities",
            field=models.FloatField(
                null=True, verbose_name="payment_from_oper_activities"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="payments_for_repurchase_of_common_stocks",
            field=models.FloatField(
                null=True,
                verbose_name="paymenys_for_repayment_of_repurchase_common_stocks",
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="proceeds_from_issuance_of_common_stocks",
            field=models.FloatField(
                null=True, verbose_name="proceeds_from_issuance_of_common_stocks"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="proceeds_from_issuance_of_long_term_debt",
            field=models.FloatField(
                null=True, verbose_name="proceeds_from_issuance_of_long_term_debt"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="proceeds_from_issuance_of_preferres_stocks",
            field=models.FloatField(
                null=True, verbose_name="proceeds_from_issuance_of_preferred_stocks"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="proceeds_from_oper_activities",
            field=models.FloatField(
                null=True, verbose_name="proceeds_from_oper_activities"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="proceeds_from_repayment_of_short_term_debt",
            field=models.FloatField(
                null=True, verbose_name="proceeds_from_repayment_of_short_term_debt"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="proceeds_from_repurchase_of_equity",
            field=models.FloatField(
                null=True, verbose_name="proceeds_of_repurchase_equity"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="proceeds_from_sale_of_treasury_stock",
            field=models.FloatField(
                null=True, verbose_name="proceeds_from_sale_of_treasury_stock"
            ),
        ),
        migrations.AlterField(
            model_name="companycashflow",
            name="profit_loss",
            field=models.FloatField(null=True, verbose_name="profit_loss"),
        ),
    ]
