# Generated by Django 4.1.7 on 2023-04-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0012_commodityprice_timeframe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodityprice",
            name="date_at",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="commodityprice",
            name="value",
            field=models.FloatField(null=True),
        ),
    ]
