# Generated by Django 4.1.7 on 2023-04-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0014_alter_indicatorvalue_date_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockprices",
            name="trade_count",
        ),
        migrations.RemoveField(
            model_name="stockprices",
            name="vwap",
        ),
    ]
