# Generated by Django 4.1.7 on 2023-04-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0017_remove_stockrisk_traynor_ratio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrisk",
            name="log_return",
            field=models.FloatField(null=True, verbose_name="log_return"),
        ),
    ]
