# Generated by Django 4.1.7 on 2023-05-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0018_stockrisk_log_return"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="topic",
        ),
    ]
