# Generated by Django 4.1.7 on 2023-05-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0019_remove_news_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="banner_image",
            field=models.URLField(max_length=500, verbose_name="banner_image"),
        ),
        migrations.AlterField(
            model_name="news",
            name="url",
            field=models.URLField(max_length=500, verbose_name="url"),
        ),
    ]
