# Generated by Django 4.1.7 on 2023-05-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0020_alter_news_banner_image_alter_news_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="banner_image",
            field=models.URLField(
                max_length=500, null=True, verbose_name="banner_image"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="score",
            field=models.FloatField(null=True, verbose_name="score"),
        ),
        migrations.AlterField(
            model_name="news",
            name="summary",
            field=models.TextField(null=True, verbose_name="summary"),
        ),
        migrations.AlterField(
            model_name="news",
            name="time_published",
            field=models.DateTimeField(null=True, verbose_name="time_published"),
        ),
        migrations.AlterField(
            model_name="news",
            name="url",
            field=models.URLField(max_length=500, null=True, verbose_name="url"),
        ),
    ]
