# Generated by Django 4.1.7 on 2023-05-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0021_alter_news_banner_image_alter_news_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newscompanyconnection",
            name="ticker_sentiment_label",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="investment.newssentiment",
            ),
        ),
        migrations.AddField(
            model_name="newscompanyconnection",
            name="ticker_sentiment_score",
            field=models.FloatField(null=True),
        ),
    ]
