# Generated by Django 4.1.7 on 2023-05-13 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0023_alter_newscompanyconnection_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="investment.newscategory",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="sentiment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="investment.newssentiment",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="investment.sourcedomain",
            ),
        ),
    ]
