# Generated by Django 4.1.7 on 2023-05-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0024_alter_news_category_alter_news_sentiment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="banner_image",
            field=models.URLField(
                max_length=1500, null=True, verbose_name="banner_image"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="url",
            field=models.URLField(max_length=1500, null=True, verbose_name="url"),
        ),
    ]
