# Generated by Django 4.1.7 on 2023-05-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0025_alter_news_banner_image_alter_news_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="banner_image",
            field=models.URLField(
                max_length=5000, null=True, verbose_name="banner_image"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="url",
            field=models.URLField(max_length=5000, null=True, verbose_name="url"),
        ),
    ]
