# Generated by Django 4.1.7 on 2023-05-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0026_alter_news_banner_image_alter_news_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="banner_image",
        ),
    ]
